### ISSUE TITLE
gtk bindings problem

### ISSUE THREAD

**Issue by schuschu** [phragment/tp-battery-icon#5]
Apparently there has been some change in your python gtk3 bindings since since 

```
loop = GObject.MainLoop(None,False)
```

no longer requires/takes the second argument. Removing it seems fine...

```
Traceback (most recent call last):
  File "/usr/bin/tp-battery-icon", line 547, in <module>
    loop = GObject.MainLoop(None,False)
  File "/usr/lib/python3.3/site-packages/gi/overrides/__init__.py", line 86, in wrapped
    return fn(*args, **kwargs)
TypeError: __new__() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by phragment** [comment]
Provisionally fixed in head.
